version: 1.0.{build}
image: Visual Studio 2022

# 安装 MinGW
install:
  - choco install mingw -y
  - refreshenv

# 设置 PATH 变量，确保 gcc 和 msys 可用
environment:
  PATH: C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;$(PATH)

build_script:
  - git submodule update --init --recursive
  - sh prepare.sh
  - echo %PATH%
  - gcc --version
  - make
  - 7z.exe a skynet_mingw.zip luaclib cservice examples lualib service test platform.dll lua54.dll skynet.dll skynet.exe C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\pthreadGC-3.dll C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\libgcc_s_dw2-1.dll

test_script:
  - skynet.exe autotest\config

artifacts:
  - path: skynet_mingw.zip
    name: skynet_mingw
