version: 1.0.{build}
build_script:
- cmd: >-
    git submodule update --init --recursive

    sh prepare.sh

    echo %PATH%

    Set Path=%path%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin

    mingw-get update

    mingw-get install mingw32-pthreads-w32-dev

    make

    7z.exe a skynet_mingw.zip luaclib cservice examples lualib service test platform.dll lua54.dll skynet.dll skynet.exe C:\MinGW\bin\pthreadGC-3.dll C:\MinGW\bin\libgcc_s_dw2-1.dll
test_script:
- cmd: skynet.exe autotest\config
artifacts:
- path: skynet_mingw.zip
  name: skynet_mingw
